name: 'Publish packages to Manticore repo'
description: 'This action publishes built packages to Manticore repo'
inputs:
  name:
    distr:
      required: true
      type: string
    arch:
      required: true
      type: string
    type:
      required: true
      type: string
    delimiter:
      required: true
      type: string
    artifact:
      required: true
      type: string
runs:
  using: "composite"
  env:
    REMOTE_SERVER: root@repo.manticoresearch.com
    SSH_KEY: ${{ secrets.REPO_SSH_KEY }}
    SSH_KEY_LOCATION: /tmp/repo.key
    TYPE: ${{ inputs.type }}
    DELIMITER: ${{ inputs.delimiter }}
  steps:
    - uses: manticoresoftware/download_artifact_with_retries@main
      with:
        name: ${{ inputs.artifact }}
        path: .
    - name: Publishing
      shell: bash
      run: |
        echo "${SSH_KEY}" > ${SSH_KEY_LOCATION}
        chmod 600 ${SSH_KEY_LOCATION}
        SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        TEMP_DIR=$(ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} "TEMP_DIR=\$(mktemp -d); if [ -z \"\$TEMP_DIR\" ]; then echo 'Failed to create temporary directory' >&2; exit 1; else echo \$TEMP_DIR; mkdir \$TEMP_DIR/build; fi")
        scp -i ${SSH_KEY_LOCATION} ${SSH_OPTS} -r build ${REMOTE_SERVER}:${TEMP_DIR}/
        ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} <<EOF
        cd ${TEMP_DIR}
        curl -sSL https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_${TYPE} > script
        chmod +x script
        DISTRO="${{ inputs.distr }}" DIGIT_DELIMITER2="${{ inputs.delimiter }}" ./script
        rm -rf ${TEMP_DIR}
        find /tmp -type d -ctime +7 -name 'tmp.*' -exec rm -rf {} \;
        EOF
